export enum ActionType {
    BOARD_START_GAME = 'BOARD_START_GAME',
    UPDATE_BOARD = 'UPDATE_BOARD',
    BOARD_RESIGN_GAME = 'BOARD_RESIGN_GAME',
    MOVE_PIECE = 'MOVE_PIECE',
    RESET_MOVE = 'RESET_MOVE',
    REMOVE_AVAILABLE_MOVES = 'REMOVE_AVAILABLE_MOVES',
    SET_AVAILABLE_MOVES = 'SET_AVAILABLE_MOVES',
}
